### PR TITLE
Frame func info and reverse methods

### PR DESCRIPTION
**Pull request by alehander92**
Including the info about a frame func and methods for reverse stepping can be very useful in some situations

### CODE REVIEW

**Comment by alehander92** [comment]
Hey, any ideas about this PR?

**Comment by baygeldin** [comment]
Hi! Thanks for the PR. It's really thorough, I appreciate it! Sorry for kind of ignoring your messages, it's really hard to find time these days. As for the changes: I've always considered reverse debugging kind of an experimetnal feature, mostly because it's not determenistic (`rr` debugger is much better in this sense), so that's why I intentionally overlooked it during development. But it definitely doesn't hurt to have convenience methods for it! Thanks, I'll try to release new version ASAP (and I'll also take a look on the other PR).

**Comment by baygeldin** [comment]
Alright, 1.3.0 is released, documentation is updated.

**Comment by alehander92** [comment]
The cool thing is that your library can be used with RR ;) thanks

**Pull request merged**
